apps/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout, name="logout")
]

travel_buddy/urls.py
from django.conf.urls import url, include
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('/main/')),
    url(r'^main/', include('apps.users.urls', namespace="users")),
    url(r'^travels/', include('apps.travels.urls', namespace="travels"))
]

apps/users/models.py
from __future__ import unicode_literals

from django.db import models

import bcrypt

# Create your models here.
class UserManager(models.Manager):
    def register(self, post_data):
        errors = []

        #name
        if len(post_data['name']) < 3:
            errors.append('Name must be at least 3 characters')
        elif len(post_data['name']) > 45:
            errors.append('Name must be under 45 characters')

        #username
        if len(post_data['username']) < 3:
            errors.append('Username must be at least 3 characters')
        elif len(post_data['username']) > 45:
            errors.append('Username must be under 45 characters')

        #password
        if len(post_data['password']) < 8:
            errors.append('Password must be at least 8 characters')
        elif post_data['password'] != post_data['password_confirmation']:
            errors.append('Passwords must match')

        if len(errors) > 0:
            return errors

        password = bcrypt.hashpw(post_data['password'].encode('utf-8'), bcrypt.gensalt())

        user = User.objects.create(
            name=post_data['name'],
            username=post_data['username'],
            password=password
        )

        return user

    def login(self, post_data):
        errors = []

        user = None
        #username
        if len(post_data['username']) < 1:
            errors.append("Username cannot be empty")
            return errors
        else:
            try:
                user = User.objects.get(username=post_data['username'])
            except:
                errors.append('Incorrect Username')
                return errors

        #password
        if bcrypt.hashpw(post_data['password'].encode('utf-8'), user.password.encode('utf-8')) == user.password:
            return user
        else:
            errors.append("Incorrect Password")
            return errors

class User(models.Model):
    name = models.CharField(max_length=45)
    username = models.CharField(max_length=16)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/users/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages

from .models import User

# Create your views here.
def index(request):
    if 'user' in request.session:
        return redirect(reverse('travels:index'))

    return render(request, 'users/index.html')

def register(request):
    if request.method == "POST":

        response = User.objects.register(request.POST)

        if type(response) is list:
            for error in response:
                messages.error(request, error)

            return redirect(reverse('users:index'))
        else:
            user = {
                'id': response.id,
                'username': response.username
            }
            request.session['user'] = user
            return redirect(reverse('travels:index'))

def login(request):
    if request.method == "POST":

        response = User.objects.login(request.POST)

        if type(response) is list:
            for error in response:
                messages.error(request, error)

            return redirect(reverse('users:index'))
        else:
            user = {
                'id': response.id,
                'username': response.username
            }
            request.session['user'] = user
            return redirect(reverse('travels:index'))

def logout(request):
    if 'user' in request.session:
        request.session.pop('user')

    return redirect(reverse('users:index'))

apps/users/templates/users/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Django Black Belt - Travel Buddy</title>
    <style media="screen">
      div{
        border: 1px solid black;
        display: inline-block;
        vertical-align: top;
        padding: 10px;
      }
      h4{
        margin: 0;
        padding: 10px 0;
      }
      label{
        width: 100px;
        display: inline-block;
      }

      .error{
        margin: 0;
        color: red;
      }
    </style>
  </head>
  <body>
    <h3>Welcome</h3>

    {% if messages %}
      {% for message in messages %}
        <p class="error">{{message}}</p>
      {% endfor %}
    {% endif %}
    <div id="register">
      <h4>Register</h4>
      <form class="" action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <p><label for="name">Name:</label><input type="text" name="name" value=""></p>
        <p><label for="username">Username:</label><input type="text" name="username" value=""></p>
        <p><label for="password">Password:</label><input type="password" name="password" value=""></p>
        <p>*Password should be at least 8 characters</p>
        <p><label for="password_confirmation">Confirm PW:</label><input type="password" name="password_confirmation" value=""></p>
        <input type="submit" name="" value="Register">
      </form>
    </div>

    <div id="login">
      <h4>Login</h4>
      <form class="" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <p><label for="username">Username:</label><input type="text" name="username" value=""></p>
        <p><label for="password">Password:</label><input type="password" name="password" value=""></p>
        <input type="submit" name="" value="Login">
      </form>
    </div>
  </body>
</html>