apps/travels/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^add$', views.add, name="add"),
    url(r'^create_trip$', views.create_trip, name="create_trip"),
    url(r'^join/(?P<trip_id>\d+?)/(?P<user_id>\d+?)$', views.join_trip, name="join_trip"),
    url(r'^destination/(?P<trip_id>\d+?)$', views.show_trip, name="show_trip")
]

apps/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout, name="logout")
]

travel_buddy/urls.py
from django.conf.urls import url, include
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('/main/')),
    url(r'^main/', include('apps.users.urls', namespace="users")),
    url(r'^travels/', include('apps.travels.urls', namespace="travels"))
]

apps/travels/models.py
from __future__ import unicode_literals

from django.db import models

from ..users.models import User

from datetime import date, datetime

# Create your models here.
class TripManager(models.Manager):
    def add_trip(self, post_data):
        errors = []
        empty_date = False

        #destination
        if len(post_data['destination']) < 1:
            errors.append("Destination cannot be empty")
        #description
        if len(post_data['description']) < 1:
            errors.append("Description cannot be empty")
        #start date (Travel date from) blank
        if len(post_data['start_date']) < 1:
            errors.append("Travel Date From cannot be empty")
            empty_date = True

        #end date (Travel date to) blank
        if len(post_data['start_date']) < 1:
            errors.append("Travel Date From cannot be empty")
            empty_date = True

        #validate dates
        if not empty_date:
            now = datetime.now()
            start_date = datetime.strptime(post_data['start_date'], '%Y-%m-%d')
            end_date = datetime.strptime(post_data['end_date'], '%Y-%m-%d')

            if start_date < now:
                errors.append("Travel Date From must be in the future")

            if end_date < start_date:
                errors.append("Travel Date To must be after Travel Date From")

        if len(errors) > 0:
            return errors

        user = User.objects.get(id=post_data['user_id'])

        Trip.objects.create(
            planned_by=user,
            destination=post_data['destination'],
            description=post_data['description'],
            start_date=start_date.date(),
            end_date=end_date.date()
        )

        return None

class Trip(models.Model):
    planned_by = models.ForeignKey(User, related_name="trips")
    joined_users = models.ManyToManyField(User, related_name="joined_trips")
    destination = models.CharField(max_length=45)
    description = models.CharField(max_length=140)
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = TripManager()

apps/travels/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages

from .models import Trip
from ..users.models import User
# Create your views here.
def index(request):
    context = {
        'user_trips': User.objects.get(id=request.session['user']['id']).trips.all()|Trip.objects.filter(joined_users__id=request.session['user']['id']).order_by('start_date'),
        'other_trips': Trip.objects.exclude(planned_by__id=request.session['user']['id']).exclude(joined_users__id=request.session['user']['id'])
    }

    return render(request, 'travels/index.html', context)

def add(request):
    return render(request, 'travels/add.html')

def create_trip(request):
    if request.method == "POST":

        response = Trip.objects.add_trip(request.POST)

        if type(response) is list:
            for error in response:
                messages.error(request, error)
            return redirect(reverse('travels:add'))

        return redirect(reverse('travels:index'))


def join_trip(request, trip_id, user_id):
    trip = Trip.objects.get(id=trip_id)
    user = None
    try:
        user = User.objects.get(id=user_id)
    except:
        messages.error(request, "User does not exist")
        return redirect(reverse('travels:index'))

    if request.session['user']['id'] == user_id:
        messages.error(request, 'Cannot join your own trip')
        return redirect(reverse('travels:index'))
    try:
        if trip.joined_users.get(id=user_id):
            messages.error(request, 'User has already joined this trip')
            return redirect(reverse('travels:show_trip', kwargs={'trip_id':trip_id}))
    except:
        trip.joined_users.add(user)
        return redirect(reverse('travels:show_trip', kwargs={'trip_id':trip_id}))

def show_trip(request, trip_id):
    context = {}

    try:
        context['trip'] = Trip.objects.get(id=trip_id)
    except:
        messages.error(request, "Trip does not exist")
        return redirect(reverse('travels:index'))

    return render(request, 'travels/show.html', context)

apps/travels/templates/travels/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Trip</title>
    <style media="screen">
      .error{
        margin: 0;
        color: red;
      }

      #header{
        height: 30px;
        position: relative;
      }
      #header a{
        vertical-align: center;
        display: inline-block;
        margin: 10px;
        position: absolute;
        right: 20px;
      }
      #header a:first-of-type{
        right: 80px;
      }

      label{
        display: inline-block;
        width: 100px;
      }

      .date{
        width: 150px;
      }
    </style>
  </head>
  <body>
    <div id="header">
      <a href="{% url 'travels:index' %}">Home</a>
      <a href="{% url 'users:logout' %}">Logout</a>
    </div>
    {% if messages %}
      {% for message in messages %}
        <p class="error">{{message}}</p>
      {% endfor %}
    {% endif %}
    <h3>Add a Trip</h3>
    <form class="" action="{% url 'travels:create_trip' %}" method="post">
      {% csrf_token %}
      <p><label for="destination">Destination:</label><input type="text" name="destination" value=""></p>
      <p><label for="description">Description:</label><input type="text" name="description" value=""></p>
      <p><label class="date" for="start_date">Travel Date From:</label><input type="date" name="start_date" value=""></p>
      <p><label class="date" for="end_date">Travel Date To:</label><input type="date" name="end_date" value=""></p>
      <input type="hidden" name="user_id" value="{{request.session.user.id}}">
      <input type="submit" name="" value="Add">
    </form>
  </body>
</html>

apps/travels/templates/travels/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Travel Dashboard</title>
    <style media="screen">
      #header{
        position: relative;
        height: 30px;
      }
      #header a{
        display: inline-block;
        vertical-align: center;
        margin: 10px;
        position: absolute;
        right: 20px;
      }

      #add{
        position: relative;
        height: 30px;
      }
      #add a{
        display: inline-block;
        vertical-align: center;
        margin: 10px;
        position: absolute;
        top: 20px;
        right: 20px;
      }
    </style>
  </head>
  <body>
    <div id="header">
      <a href="{% url 'users:logout' %}">Logout</a>
    </div>
    <h3>Hello, {{request.session.user.username.title}}!</h3>
    <div id="user_trips">
      <h4>Your Trip Schedules</h4>
      <table>
        <thead>
          <tr>
            <th>Destination</th>
            <th>Travel Start Date</th>
            <th>Travel End Date</th>
            <th>Plan</th>
          </tr>
        </thead>
        <tbody>
        {% if user_trips %}
          {% for trip in user_trips %}
          <tr>
            <td>{{trip.destination}}</td>
            <td>{{trip.start_date}}</td>
            <td>{{trip.end_date}}</td>
            <td>{{trip.description}}</td>
          </tr>
          {% endfor %}
        {% endif %}
        </tbody>
      </table>
    </div>

    <div id="other_trips">
      <h4>Other User's Travel Plans</h4>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Destination</th>
            <th>Travel Start Date</th>
            <th>Travel End Date</th>
            <th>Do You Want To Join</th>
          </tr>
        </thead>
        <tbody>
        {% if other_trips %}
          {% for trip in other_trips %}
          <tr>
            <td>{{trip.planned_by.name}}</td>
            <td>{{trip.destination}}</td>
            <td>{{trip.start_date}}</td>
            <td>{{trip.end_date}}</td>
            <td><a href="{% url 'travels:join_trip' trip_id=trip.id user_id=request.session.user.id %}">Join</a></td>
          </tr>
        </tbody>
        {% endfor %}
      {% endif %}
      </table>
    </div>

    <div id="add">
      <a href="{% url 'travels:add' %}">Add Travel Plan</a>
    </div>
  </body>
</html>

apps/travels/templates/travels/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Destination</title>
    <style media="screen">
    #header{
      position: relative;
      height: 30px;
    }
    #header a{
      display: inline-block;
      vertical-align: center;
      margin: 10px;
      position: absolute;
      right: 20px;
    }
    #header a:first-of-type{
      right: 80px;
    }

    ul{
      list-style: none;
    }

    .error{
      color: red;
      margin: 0;
    }
    </style>
  </head>
  <body>
    <div id="header">
      <a href="{% url 'travels:index' %}">Home</a>
      <a href="{% url 'users:logout' %}">Logout</a>
    </div>
    {% if messages %}
      {% for message in messages %}
      <p class="error">{{message}}</p>
      {% endfor %}
    {% endif %}

    <h3>{{trip.destination}}</h3>
    <ul>
      <li><label>Planned By:</label> {{trip.planned_by.name}}</li>
      <li><label>Description:</label> {{trip.description}}</li>
      <li><label>Travel Date From:</label> {{trip.start_date}}</li>
      <li><label>Travel Date To:</label> {{trip.end_date}}</li>
    </ul>

    <h4>Other users' joining the trip:</h4>
    {% if trip.joined_users %}
    <ul>
      {% for user in trip.joined_users.all %}
      <li>{{user.name}}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </body>
</html>